import { ensurePkmnBuilder } from './types'

export const paldeaBuilder = {
  'potw-128-combat_breed': ensurePkmnBuilder({
    species: 'Tauros', type1: 'Fighting',
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 115, eggBase: 'potw-128-combat_breed', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `This Pokémon has a muscular body and excels at close-quarters combat. It uses its short horns to strike the opponent’s weak spots.`,
    hp: 75, attack: 110, defense: 105, spAttack: 30, spDefense: 70, speed: 100,
    move: ['Raging Bull'],
    moveTMs: [],
  }),
  'potw-128-blaze_breed': ensurePkmnBuilder({
    species: 'Tauros', type1: 'Fighting', type2: 'Fire',
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 85, eggBase: 'potw-128-blaze_breed', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `When heated by fire energy, its horns can get hotter than 1,800 degrees Fahrenheit. Those gored by them will suffer both wounds and burns.`,
    hp: 75, attack: 110, defense: 105, spAttack: 30, spDefense: 70, speed: 100,
    move: ['Raging Bull', 'Double Kick'],
    moveTMs: [],
  }),
  'potw-128-aqua_breed': ensurePkmnBuilder({
    species: 'Tauros', type1: 'Fighting', type2: 'Water',
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 110, eggBase: 'potw-128-aqua_breed', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `This Pokémon blasts water from holes on the tips of its horns—the high-pressure jets pierce right through Tauros’s enemies.`,
    hp: 75, attack: 110, defense: 105, spAttack: 30, spDefense: 70, speed: 100,
    move: ['Raging Bull', 'Double Kick'],
    moveTMs: [],
  }),
  'potw-194-paldean': ensurePkmnBuilder({
    species: 'Wooper', type1: 'Poison', type2: 'Ground', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 11,
    eggBase: 'potw-194-paldean', eggGroup: ['Water 1', 'Field'], eggCycles: 20,
    levelAt: 20, levelTo: 'potw-980', // FIXME
    pokedex: `After losing a territorial struggle, Wooper began living on land. The Pokémon changed over time, developing a poisonous film to protect its body.`,
    hp: 55, attack: 45, defense: 45, spAttack: 25, spDefense: 25, speed: 15,
    move: ['Poison Tail', 'Mud Shot'],
    moveTMs: []
  }),
  'potw-901-blood_moon': ensurePkmnBuilder({
    species: 'Ursaluna', type1: 'Ground', type2: 'Normal', 
    tiers: ['Traditional' /* 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 290,
    eggBase: 'potw-216', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `It crossed the sea and drifted ashore in a new land. Surviving in this place led it to take on a unique appearance and gain special powers.`,
    hp: 113, attack: 70, defense: 120, spAttack: 135, spDefense: 65, speed: 52,
    move: ['Earth Power', 'Blood Moon'],
    moveTMs: [
      'Hyper Beam', 'Ice Punch', 'Thunder Punch', 'Fire Punch', 'Snore', 
      'Double-Edge', 'Dig', 'Earthquake', 'Fury Cutter', 'Swift', 
      'Rock Tomb', 'Facade', 'Aerial Ace', 'Rock Slide', 'Stone Edge', 
      'Close Combat', 'Shadow Claw', 'Hyper Voice', 'Bulldoze', 'Play Rough', 
      'Giga Impact', 'Body Press', 'Payback', 'Protect', 'Metronome', 
      'Bulk Up', 'Swords Dance', 'Sunny Day', 'Rain Dance', 'Belly Drum', 
      'Charm', 'Substitute', 'Endure', 'Sweet Scent', 'Taunt', 
      'Fake Tears', 
    ],
    novelMoves: [[],
      ['Focus Blast', 'Calm Mind'],
      ['Moonblast', 'Belly Drum'],
      ['Vacuum Wave', 'Scary Face'],
      ['Snarl', 'Substitute'],
    ],
  }),
  'potw-906': ensurePkmnBuilder({
    species: 'Sprigatito', type1: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 4.1,
    eggBase: 'potw-906', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 16, levelTo: 'potw-906', // FIXME
    pokedex: `Its fluffy fur is similar in composition to plants. This Pokémon frequently washes its face to keep it from drying out.`,
    hp: 40, attack: 61, defense: 54, spAttack: 45, spDefense: 45, speed: 65,
    move: ['Leafage'],
    moveTMs: []
  }),
  'potw-907': ensurePkmnBuilder({
    species: 'Floragato', type1: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 12.2,
    eggBase: 'potw-906', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 36, levelTo: 'potw-908',
    pokedex: `Floragato deftly wields the vine hidden beneath its long fur, slamming the hard flower bud against its opponents.`,
    hp: 61, attack: 80, defense: 63, spAttack: 60, spDefense: 63, speed: 83,
    move: ['Seed Bomb'],
    moveTMs: []
  }),
  'potw-908': ensurePkmnBuilder({
    species: 'Meowscarada', type1: 'Grass', type2: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 31.2,
    eggBase: 'potw-906', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `This Pokémon uses the reflective fur lining its cape to camouflage the stem of its flower, creating the illusion that the flower is floating.`,
    hp: 76, attack: 110, defense: 70, spAttack: 81, spDefense: 70, speed: 123,
    move: ['Flower Trick', 'Night Slash'],
    moveTMs: []
  }),
  'potw-909': ensurePkmnBuilder({
    species: 'Fuecoco', type1: 'Fire', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 9.8,
    eggBase: 'potw-909', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 16, levelTo: 'potw-910',
    pokedex: `It lies on warm rocks and uses the heat absorbed by its square-shaped scales to create fire energy.`,
    hp: 67, attack: 45, defense: 59, spAttack: 63, spDefense: 40, speed: 36,
    move: ['Ember'],
    moveTMs: []
  }),
  'potw-910': ensurePkmnBuilder({
    species: 'Crocalor', type1: 'Fire', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 30.7,
    eggBase: 'potw-909', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 36, levelTo: 'potw-911',
    pokedex: `The combination of Crocalor's fire energy and overflowing vitality has caused an egg-shaped fireball to appear on the Pokémon's head.`,
    hp: 81, attack: 55, defense: 78, spAttack: 90, spDefense: 58, speed: 49,
    move: ['Incinerate'],
    moveTMs: []
  }),
  'potw-911': ensurePkmnBuilder({
    species: 'Skeledirge', type1: 'Fire', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 326.5,
    eggBase: 'potw-909', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `The fiery bird changes shape when Skeledirge sings. Rumor has it that the bird was born when the fireball on Skeledirge's head gained a soul.`,
    hp: 104, attack: 75, defense: 100, spAttack: 110, spDefense: 75, speed: 66,
    move: ['Torch Song', 'Shadow Ball'],
    moveTMs: []
  }),
  'potw-912': ensurePkmnBuilder({
    species: 'Quaxly', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 6.1,
    eggBase: 'potw-912', eggGroup: ['Flying', 'Water 1'], eggCycles: 10,
    levelAt: 16, levelTo: 'potw-913',
    pokedex: `This Pokémon migrated to Paldea from distant lands long ago. The gel secreted by its feathers repels water and grime.`,
    hp: 55, attack: 65, defense: 45, spAttack: 50, spDefense: 45, speed: 50,
    move: ['Water Gun'],
    moveTMs: []
  }),
  'potw-913': ensurePkmnBuilder({
    species: 'Quaxwell', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 21.5,
    eggBase: 'potw-912', eggGroup: ['Flying', 'Water 1'], eggCycles: 10,
    levelAt: 36, levelTo: 'potw-914',
    pokedex: `These Pokémon constantly run through shallow waters to train their legs, then compete with each other to see which of them kicks most gracefully.`,
    hp: 70, attack: 85, defense: 65, spAttack: 65, spDefense: 60, speed: 65,
    move: ['Aqua Cutter'],
    moveTMs: []
  }),
  'potw-914': ensurePkmnBuilder({
    species: 'Quaquaval', type1: 'Water', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 61.9,
    eggBase: 'potw-912', eggGroup: ['Flying', 'Water 1'], eggCycles: 10,
    pokedex: `A single kick from a Quaquaval can send a truck rolling. This Pokémon uses its powerful legs to perform striking dances from far-off lands.`,
    hp: 85, attack: 120, defense: 80, spAttack: 85, spDefense: 75, speed: 85,
    move: ['Aqua Step', 'Close Combat'],
    moveTMs: []
  }),
  'potw-915': ensurePkmnBuilder({ // TODO: Genders
    species: 'Lechonk', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 10.2, gender: ['male', 'female'],
    eggBase: 'potw-915', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 18, levelTo: 'potw-916',
    pokedex: `It searches for food all day. It possesses a keen sense of smell but doesn't use it for anything other than foraging.`,
    hp: 54, attack: 45, defense: 40, spAttack: 35, spDefense: 45, speed: 35,
    move: ['Tackle'],
    moveTMs: []
  }),
  // TODO: Oinky has gendered stats
  // https://serebii.net/pokedex-sv/oinkologne/
  'potw-916': ensurePkmnBuilder({
    species: 'Oinkologne', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 120, gender: ['male', 'female'],
    eggBase: 'potw-915', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `Oinkologne is proud of its fine, glossy skin. It emits a concentrated scent from the tip of its tail.`,
    hp: 110, attack: 100, defense: 75, spAttack: 59, spDefense: 80, speed: 65,
    move: ['Double-Edge'],
    moveTMs: []
  }),
  'potw-916-female': ensurePkmnBuilder({
    species: 'Oinkologne', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 120,
    eggBase: 'potw-915', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `This Pokémon sends a flowerlike scent wafting about. Well-developed muscles in its legs allow it to leap more than 16 feet with no trouble at all.`,
    hp: 115, attack: 90, defense: 70, spAttack: 59, spDefense: 90, speed: 65,
    move: ['Double-Edge'],
    moveTMs: []
  }),
  'potw-917': ensurePkmnBuilder({
    species: 'Tarountula', type1: 'Bug', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 4,
    eggBase: 'potw-917', eggGroup: ['Bug'], eggCycles: 10,
    levelAt: 15, levelTo: 'potw-918',
    pokedex: `The ball of threads wrapped around its body is elastic enough to deflect the scythes of Scyther, this Pokémon's natural enemy.`,
    hp: 35, attack: 41, defense: 45, spAttack: 29, spDefense: 40, speed: 20,
    move: ['Struggle Bug'],
    moveTMs: []
  }),
  'potw-918': ensurePkmnBuilder({
    species: 'Spidops', type1: 'Bug', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 16.5,
    eggBase: 'potw-917', eggGroup: ['Bug'], eggCycles: 10,
    pokedex: `It clings to branches and ceilings using its threads and moves without a sound. It takes out its prey before the prey even notices it.`,
    hp: 60, attack: 79, defense: 92, spAttack: 52, spDefense: 86, speed: 35,
    move: ['Skitter Smack'],
    moveTMs: []
  }),
  'potw-919': ensurePkmnBuilder({
    species: 'Nymble', type1: 'Bug', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 1,
    eggBase: 'potw-919', eggGroup: ['Bug'], eggCycles: 10,
    levelAt: 24, levelTo: 'potw-920',
    pokedex: `It has its third set of legs folded up. When it's in a tough spot, this Pokémon jumps over 30 feet using the strength of its legs.`,
    hp: 33, attack: 46, defense: 40, spAttack: 21, spDefense: 25, speed: 45,
    move: ['Struggle Bug'],
    moveTMs: []
  }),
  'potw-920': ensurePkmnBuilder({
    species: 'Lokix', type1: 'Bug', type2: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 17.5,
    eggBase: 'potw-919', eggGroup: ['Bug'], eggCycles: 10,
    pokedex: `When it decides to fight all out, it stands on its previously folded legs to enter Showdown Mode. It neutralizes its enemies in short order.`,
    hp: 71, attack: 102, defense: 78, spAttack: 52, spDefense: 55, speed: 92,
    move: ['Lunge', 'Sucker Punch'],
    moveTMs: [],
    novelMoves: [[],
      ['Axe Kick', 'Screech'],
    ]
  }),
  'potw-921': ensurePkmnBuilder({
    species: 'Pawmi', type1: 'Electric', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 2.5,
    eggBase: 'potw-921', eggGroup: ['Field'], eggCycles: 15,
    levelAt: 18, levelTo: 'potw-922',
    pokedex: `It has underdeveloped electric sacs on its cheeks. These sacs can produce electricity only if Pawmi rubs them furiously with the pads on its forepaws.`,
    hp: 45, attack: 50, defense: 20, spAttack: 40, spDefense: 25, speed: 60,
    move: ['Thunder Shock'],
    moveTMs: []
  }),
  'potw-922': ensurePkmnBuilder({
    species: 'Pawmo', type1: 'Electric', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 6.5,
    eggBase: 'potw-921', eggGroup: ['Field'], eggCycles: 15,
    evolveTo: ['potw-923'],
    pokedex: `When its group is attacked, Pawmo is the first to leap into battle, defeating enemies with a fighting technique that utilizes electric shocks.`,
    hp: 60, attack: 75, defense: 40, spAttack: 50, spDefense: 40, speed: 85,
    move: ['Spark', 'Arm Thrust'],
    moveTMs: []
  }),
  'potw-923': ensurePkmnBuilder({
    species: 'Pawmot', type1: 'Electric', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 41,
    eggBase: 'potw-921', eggGroup: ['Field'], eggCycles: 15,
    pokedex: `This Pokémon normally is slow to react, but once it enters battle, it will strike down its enemies with lightning-fast movements.`,
    hp: 70, attack: 115, defense: 70, spAttack: 70, spDefense: 60, speed: 105,
    move: ['Double Shock', 'Close Combat'],
    moveTMs: [],
    novelMoves: [[],
      // ['Revival Blessing'],
    ],
  }),
  'potw-924': ensurePkmnBuilder({
    species: 'Tandemaus', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 1.8,
    eggBase: 'potw-924', eggGroup: ['Field'], eggCycles: 5,
    levelAt: 25, levelTo: 'potw-925',
    pokedex: `Exhibiting great teamwork, they use their incisors to cut pieces out of any material that might be useful for a nest, then make off with them.`,
    hp: 50, attack: 50, defense: 45, spAttack: 40, spDefense: 45, speed: 75,
    move: ['Double Hit'],
    moveTMs: []
  }),
  'potw-925': ensurePkmnBuilder({
    species: 'Maushold', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 2.8, syncableForms: [...Array(99).fill('family_of_four'), 'family_of_three'], needForm: true,
    eggBase: 'potw-924', eggGroup: ['Field'], eggCycles: 5,
    pokedex: `The two little ones just appeared one day. The group might be a family of related Pokémon, but nobody knows for sure.`,
    hp: 74, attack: 75, defense: 70, spAttack: 65, spDefense: 75, speed: 111,
    move: ['Population Bomb'],
    moveTMs: []
  }),
  'potw-926': ensurePkmnBuilder({
    species: 'Fidough', type1: 'Fairy', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 10.9,
    eggBase: 'potw-926', eggGroup: ['Field', 'Mineral'], eggCycles: 10,
    levelAt: 26, levelTo: 'potw-927',
    pokedex: `This Pokémon is smooth and moist to the touch. Yeast in Fidough's breath induces fermentation in the Pokémon's vicinity.`,
    hp: 37, attack: 55, defense: 70, spAttack: 30, spDefense: 55, speed: 65,
    move: ['Play Rough'],
    moveTMs: []
  }),
  'potw-927': ensurePkmnBuilder({
    species: 'Dachsbun', type1: 'Fairy', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 14.9,
    eggBase: 'potw-926', eggGroup: ['Field', 'Mineral'], eggCycles: 10,
    pokedex: `The pleasant aroma that emanates from this Pokémon's body helps wheat grow, so Dachsbun has been treasured by farming villages.`,
    hp: 57, attack: 80, defense: 115, spAttack: 50, spDefense: 80, speed: 95,
    move: ['Play Rough'],
    moveTMs: []
  }),
  'potw-928': ensurePkmnBuilder({
    species: 'Smoliv', type1: 'Grass', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 6.5,
    eggBase: 'potw-928', eggGroup: ['Grass'], eggCycles: 10,
    levelAt: 25, levelTo: 'potw-929',
    pokedex: `It protects itself from enemies by emitting oil from the fruit on its head. This oil is bitter and astringent enough to make someone flinch.`,
    hp: 41, attack: 35, defense: 45, spAttack: 58, spDefense: 51, speed: 30,
    move: ['Absorb'],
    moveTMs: []
  }),
  'potw-929': ensurePkmnBuilder({
    species: 'Dolliv', type1: 'Grass', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 11.9,
    eggBase: 'potw-928', eggGroup: ['Grass'], eggCycles: 10,
    levelAt: 35, levelTo: 'potw-930',
    pokedex: `Dolliv shares its tasty, fresh-scented oil with others. This species has coexisted with humans since times long gone.`,
    hp: 52, attack: 53, defense: 60, spAttack: 78, spDefense: 78, speed: 33,
    move: ['Mega Drain'],
    moveTMs: []
  }),
  'potw-930': ensurePkmnBuilder({
    species: 'Arboliva', type1: 'Grass', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 48.2,
    eggBase: 'potw-928', eggGroup: ['Grass'], eggCycles: 10,
    pokedex: `This calm Pokémon is very compassionate. It will share its delicious, nutrient-rich oil with weakened Pokémon.`,
    hp: 78, attack: 69, defense: 90, spAttack: 125, spDefense: 109, speed: 39,
    move: ['Petal Dance'],
    moveTMs: []
  }),
  'potw-931': ensurePkmnBuilder({
    species: 'Squawkabilly', type1: 'Normal', type2: 'Flying', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    syncableForms: ['green_plumage', 'white_plumage', 'blue_plumage', 'yellow_plumage'], needForm: true,
    weight: 2.4,
    eggBase: 'potw-931', eggGroup: ['Flying'], eggCycles: 15,
    pokedex: `These Pokémon prefer to live in cities. They form flocks based on the color of their feathers, and they fight over territory.`,
    hp: 82, attack: 96, defense: 51, spAttack: 45, spDefense: 51, speed: 92,
    move: ['Uproar', 'Fly'],
    moveTMs: []
  }),
  'potw-932': ensurePkmnBuilder({
    species: 'Nacli', type1: 'Rock', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 16,
    eggBase: 'potw-932', eggGroup: ['Mineral'], eggCycles: 10,
    levelAt: 24, levelTo: 'potw-933',
    pokedex: `It was born in a layer of rock salt deep under the earth. This species was particularly treasured in the old days, as they would share precious salt.`,
    hp: 55, attack: 55, defense: 75, spAttack: 35, spDefense: 35, speed: 25,
    move: ['Rock Throw'],
    moveTMs: []
  }),
  'potw-933': ensurePkmnBuilder({
    species: 'Naclstack', type1: 'Rock', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 105,
    eggBase: 'potw-932', eggGroup: ['Mineral'], eggCycles: 10,
    levelAt: 38, levelTo: 'potw-934',
    pokedex: `This Pokémon dry cures its prey by spraying salt over them. The curing process steals away the water in the prey's body.`,
    hp: 60, attack: 60, defense: 100, spAttack: 35, spDefense: 65, speed: 35,
    move: ['Rock Slide'],
    moveTMs: []
  }),
  'potw-934': ensurePkmnBuilder({
    species: 'Garganacl', type1: 'Rock', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 240,
    eggBase: 'potw-932', eggGroup: ['Mineral'], eggCycles: 10,
    pokedex: `Garganacl will rub its fingertips together and sprinkle injured Pokémon with salt. Even severe wounds will promptly heal afterward.`,
    hp: 100, attack: 100, defense: 130, spAttack: 45, spDefense: 90, speed: 35,
    move: ['Stone Edge'],
    moveTMs: []
  }),
  'potw-935': ensurePkmnBuilder({
    species: 'Charcadet', type1: 'Fire', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 10.5,
    eggBase: 'potw-935', eggGroup: ['Human-Like'], eggCycles: 15,
    evolveTo: ['potw-936', 'potw-937'],
    pokedex: `Burnt charcoal came to life and became a Pokémon. Possessing a fiery fighting spirit, Charcadet will battle even tough opponents.`,
    hp: 40, attack: 50, defense: 40, spAttack: 50, spDefense: 40, speed: 35,
    move: ['Flame Charge'],
    moveTMs: []
  }),
  'potw-936': ensurePkmnBuilder({
    species: 'Armarouge', type1: 'Fire', type2: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 85,
    eggBase: 'potw-935', eggGroup: ['Human-Like'], eggCycles: 15,
    pokedex: `Armarouge evolved through the use of a set of armor that belonged to a distinguished warrior. This Pokémon is incredibly loyal.`,
    hp: 85, attack: 60, defense: 100, spAttack: 125, spDefense: 80, speed: 75,
    move: ['Armor Cannon', 'Psyshock'],
    moveTMs: []
  }),
  'potw-937': ensurePkmnBuilder({
    species: 'Ceruledge', type1: 'Fire', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 62,
    eggBase: 'potw-935', eggGroup: ['Human-Like'], eggCycles: 15,
    pokedex: `The fiery blades on its arms burn fiercely with the lingering resentment of a sword wielder who fell before accomplishing their goal.`,
    hp: 75, attack: 125, defense: 80, spAttack: 60, spDefense: 100, speed: 85,
    move: ['Bitter Blade', 'Shadow Claw'],
    moveTMs: []
  }),
  'potw-938': ensurePkmnBuilder({
    species: 'Tadbulb', type1: 'Electric', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 0.4,
    eggBase: 'potw-938', eggGroup: ['Water 1'], eggCycles: 10,
    evolveTo: ['potw-939'],
    pokedex: `Tadbulb shakes its tail to generate electricity. If it senses danger, it will make its head blink on and off to alert its allies.`,
    hp: 61, attack: 31, defense: 41, spAttack: 59, spDefense: 35, speed: 45,
    move: ['Thunder Shock'],
    moveTMs: []
  }),
  'potw-939': ensurePkmnBuilder({
    species: 'Bellibolt', type1: 'Electric', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 113,
    eggBase: 'potw-938', eggGroup: ['Water 1'], eggCycles: 10,
    pokedex: `When this Pokémon expands and contracts its wobbly body, the belly-button dynamo in its stomach produces a huge amount of electricity.`,
    hp: 109, attack: 64, defense: 91, spAttack: 103, spDefense: 83, speed: 45,
    move: ['Zap Cannon'],
    moveTMs: []
  }),
  'potw-940': ensurePkmnBuilder({
    species: 'Wattrel', type1: 'Electric', type2: 'Flying', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 3.6,
    eggBase: 'potw-940', eggGroup: ['Water 1'], eggCycles: 10,
    levelAt: 25, levelTo: 'potw-941',
    pokedex: `When its wings catch the wind, the bones within produce electricity. This Pokémon dives into the ocean, catching prey by electrocuting them.`,
    hp: 40, attack: 40, defense: 35, spAttack: 55, spDefense: 40, speed: 70,
    move: ['Spark', 'Pluck'],
    moveTMs: []
  }),
  'potw-941': ensurePkmnBuilder({
    species: 'Kilowattrel', type1: 'Electric', type2: 'Flying', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 38.6,
    eggBase: 'potw-940', eggGroup: ['Water 1'], eggCycles: 10,
    pokedex: `Kilowattrel inflates its throat sac to amplify its electricity. By riding the wind, this Pokémon can fly over 430 miles in a day.`,
    hp: 70, attack: 70, defense: 60, spAttack: 105, spDefense: 60, speed: 125,
    move: ['Electro Ball', 'Dual Wingbeat'],
    moveTMs: []
  }),
  'potw-942': ensurePkmnBuilder({
    species: 'Maschiff', type1: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 16,
    eggBase: 'potw-942', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 30, levelTo: 'potw-943',
    pokedex: `It always scowls in an attempt to make opponents take it seriously, but even crying children will burst into laughter when they see Maschiff's face.`,
    hp: 60, attack: 78, defense: 60, spAttack: 40, spDefense: 51, speed: 51,
    move: ['Bite'],
    moveTMs: []
  }),
  'potw-943': ensurePkmnBuilder({
    species: 'Mabosstiff', type1: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 61,
    eggBase: 'potw-942', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `This Pokémon can store energy in its large dewlap. Mabosstiff unleashes this energy all at once to blow away enemies.`,
    hp: 80, attack: 120, defense: 90, spAttack: 60, spDefense: 70, speed: 85,
    move: ['Crunch'],
    moveTMs: []
  }),
  'potw-944': ensurePkmnBuilder({
    species: 'Shroodle', type1: 'Poison', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 0.7,
    eggBase: 'potw-944', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 28, levelTo: 'potw-945',
    pokedex: `Though usually a mellow Pokémon, it will sink its sharp, poison-soaked front teeth into any that anger it, causing paralysis in the object of its ire.`,
    hp: 40, attack: 65, defense: 35, spAttack: 40, spDefense: 35, speed: 75,
    move: ['Poison Fang', 'Fury Swipes'],
    moveTMs: []
  }),
  'potw-945': ensurePkmnBuilder({
    species: 'Grafaiai', type1: 'Poison', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 27.2,
    eggBase: 'potw-944', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `The color of the poisonous saliva depends on what the Pokémon eats. Grafaiai covers its fingers in its saliva and draws patterns on trees in forests.`,
    hp: 63, attack: 95, defense: 65, spAttack: 80, spDefense: 72, speed: 110,
    move: ['Poison Jab', 'Slash'],
    moveTMs: []
  }),
  'potw-946': ensurePkmnBuilder({
    species: 'Bramblin', type1: 'Grass', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 0.6,
    eggBase: 'potw-946', eggGroup: ['Grass'], eggCycles: 10,
    evolveTo: ['potw-947'],
    pokedex: `A soul unable to move on to the afterlife was blown around by the wind until it got tangled up with dried grass and became a Pokémon.`,
    hp: 40, attack: 65, defense: 30, spAttack: 45, spDefense: 35, speed: 60,
    move: ['Bullet Seed', 'Astonish'],
    moveTMs: []
  }),
  'potw-947': ensurePkmnBuilder({
    species: 'Brambleghast', type1: 'Grass', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 6,
    eggBase: 'potw-946', eggGroup: ['Grass'], eggCycles: 10,
    pokedex: `It will open the branches of its head to envelop its prey. Once it absorbs all the life energy it needs, it expels the prey and discards it.`,
    hp: 55, attack: 115, defense: 70, spAttack: 80, spDefense: 70, speed: 90,
    move: ['Power Whip', 'Phantom Force'],
    moveTMs: []
  }),
  'potw-948': ensurePkmnBuilder({
    species: 'Toedscool', type1: 'Ground', type2: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 33,
    eggBase: 'potw-948', eggGroup: ['Grass'], eggCycles: 10,
    levelAt: 30, levelTo: 'potw-949',
    pokedex: `Toedscool lives in muggy forests. The flaps that fall from its body are chewy and very delicious.`,
    hp: 40, attack: 40, defense: 35, spAttack: 50, spDefense: 100, speed: 70,
    move: ['Mud-Slap', 'Mega Drain'],
    moveTMs: []
  }),
  'potw-949': ensurePkmnBuilder({
    species: 'Toedscruel', type1: 'Ground', type2: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 58,
    eggBase: 'potw-948', eggGroup: ['Grass'], eggCycles: 10,
    pokedex: `These Pokémon gather into groups and form colonies deep within forests. They absolutely hate it when strangers approach.`,
    hp: 80, attack: 70, defense: 65, spAttack: 80, spDefense: 120, speed: 100,
    move: ['Earth Power', 'Power Whip'],
    moveTMs: []
  }),
  'potw-950': ensurePkmnBuilder({
    species: 'Klawf', type1: 'Rock', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 79,
    eggBase: 'potw-950', eggGroup: ['Water 3'], eggCycles: 35,
    pokedex: `Klawf hangs upside-down from cliffs, waiting for prey. But Klawf can't remain in this position for long because its blood rushes to its head.`,
    hp: 70, attack: 100, defense: 115, spAttack: 35, spDefense: 55, speed: 75,
    move: ['Rock Blast'],
    moveTMs: []
  }),
  'potw-951': ensurePkmnBuilder({
    species: 'Capsakid', type1: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 3,
    eggBase: 'potw-951', eggGroup: ['Grass'], eggCycles: 10,
    evolveTo: ['potw-952'],
    pokedex: `The more sunlight this Pokémon bathes in, the more spicy chemicals are produced by its body, and thus the spicier its moves become.`,
    hp: 50, attack: 62, defense: 40, spAttack: 62, spDefense: 40, speed: 50,
    move: ['Leafage'],
    moveTMs: []
  }),
  'potw-952': ensurePkmnBuilder({
    species: 'Scovillain', type1: 'Grass', type2: 'Fire', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 15,
    eggBase: 'potw-951', eggGroup: ['Grass'], eggCycles: 10,
    pokedex: `The red head converts spicy chemicals into fire energy and blasts the surrounding area with a super spicy stream of flame.`,
    hp: 65, attack: 108, defense: 65, spAttack: 108, spDefense: 65, speed: 75,
    move: ['Bullet Seed', 'Flamethrower'],
    moveTMs: [],
    novelMoves: [[],
      ['Zen Headbutt', 'Spicy Extract'],
    ],
  }),
  'potw-953': ensurePkmnBuilder({
    species: 'Rellor', type1: 'Bug', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 1,
    eggBase: 'potw-953', eggGroup: ['Bug'], eggCycles: 10,
    evolveTo: ['potw-954'],
    pokedex: `This Pokémon creates a mud ball by mixing sand and dirt with psychic energy. It treasures its mud ball more than its own life.`,
    hp: 41, attack: 50, defense: 60, spAttack: 31, spDefense: 58, speed: 30,
    move: ['Bug Bite'],
    moveTMs: []
  }),
  'potw-954': ensurePkmnBuilder({
    species: 'Rabsca', type1: 'Bug', type2: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 3.5,
    eggBase: 'potw-953', eggGroup: ['Bug'], eggCycles: 10,
    pokedex: `The body that supports the ball barely moves. Therefore, it is thought that the true body of this Pokémon is actually inside the ball.`,
    hp: 75, attack: 50, defense: 85, spAttack: 115, spDefense: 100, speed: 45,
    move: ['Bug Buzz', 'Psychic'],
    moveTMs: [],
    novelMoves: [[],
      // ['Revival Blessing'],
    ],
  }),
  'potw-955': ensurePkmnBuilder({
    species: 'Flittle', type1: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 1.5,
    eggBase: 'potw-955', eggGroup: ['Flying'], eggCycles: 10,
    levelAt: 35, levelTo: 'potw-956',
    pokedex: `Flittle's toes levitate about half an inch above the ground because of the psychic power emitted from the frills on the Pokémon's belly.`,
    hp: 30, attack: 35, defense: 30, spAttack: 55, spDefense: 30, speed: 75,
    move: ['Confusion'],
    moveTMs: []
  }),
  'potw-956': ensurePkmnBuilder({
    species: 'Espathra', type1: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 90,
    eggBase: 'potw-955', eggGroup: ['Flying'], eggCycles: 10,
    pokedex: `It immobilizes opponents by bathing them in psychic power from its large eyes. Despite its appearance, it has a vicious temperament.`,
    hp: 95, attack: 60, defense: 60, spAttack: 101, spDefense: 60, speed: 105,
    move: ['Lumina Crash'],
    moveTMs: []
  }),
  'potw-957': ensurePkmnBuilder({
    species: 'Tinkatink', type1: 'Fairy', type2: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 8.9,
    eggBase: 'potw-957', eggGroup: ['Fairy'], eggCycles: 10,
    levelAt: 24, levelTo: 'potw-958',
    pokedex: `It swings its handmade hammer around to protect itself, but the hammer is often stolen by Pokémon that eat metal.`,
    hp: 50, attack: 45, defense: 45, spAttack: 35, spDefense: 64, speed: 58,
    move: ['Fairy Wind', 'Metal Claw'],
    moveTMs: []
  }),
  'potw-958': ensurePkmnBuilder({
    species: 'Tinkatuff', type1: 'Fairy', type2: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 59.1,
    eggBase: 'potw-957', eggGroup: ['Fairy'], eggCycles: 10,
    levelAt: 38, levelTo: 'potw-959',
    pokedex: `This Pokémon will attack groups of Pawniard and Bisharp, gathering metal from them in order to create a large and sturdy hammer.`,
    hp: 65, attack: 55, defense: 55, spAttack: 45, spDefense: 82, speed: 78,
    move: ['Draining Kiss', 'Flash Cannon'],
    moveTMs: []
  }),
  'potw-959': ensurePkmnBuilder({
    species: 'Tinkaton', type1: 'Fairy', type2: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 112.8,
    eggBase: 'potw-957', eggGroup: ['Fairy'], eggCycles: 10,
    pokedex: `This intelligent Pokémon has a very daring disposition. It knocks rocks into the sky with its hammer, aiming for flying Corviknight.`,
    hp: 85, attack: 75, defense: 77, spAttack: 70, spDefense: 105, speed: 94,
    move: ['Play Rough', 'Gigaton Hammer'],
    moveTMs: []
  }),
  'potw-960': ensurePkmnBuilder({
    species: 'Wiglett', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 1.8,
    eggBase: 'potw-960', eggGroup: ['Water 3'], eggCycles: 10,
    levelAt: 26, levelTo: 'potw-961',
    pokedex: `This Pokémon can pick up the scent of a Veluza just over 65 feet away and will hide itself in the sand.`,
    hp: 10, attack: 55, defense: 25, spAttack: 35, spDefense: 25, speed: 95,
    move: ['Aqua Jet'],
    moveTMs: []
  }),
  'potw-961': ensurePkmnBuilder({
    species: 'Wugtrio', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 5.4,
    eggBase: 'potw-960', eggGroup: ['Water 3'], eggCycles: 10,
    pokedex: `It has a vicious temperament, contrary to what its appearance may suggest. It wraps its long bodies around prey, then drags the prey into its den.`,
    hp: 35, attack: 100, defense: 50, spAttack: 50, spDefense: 70, speed: 120,
    move: ['Triple Dive'],
    moveTMs: []
  }),
  'potw-962': ensurePkmnBuilder({
    species: 'Bombirdier', type1: 'Flying', type2: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 42.9,
    eggBase: 'potw-962', eggGroup: ['Flying'], eggCycles: 20,
    pokedex: `It gathers things up in an apron made from shed feathers added to the Pokémon's chest feathers, then drops those things from high places for fun.`,
    hp: 70, attack: 103, defense: 85, spAttack: 60, spDefense: 85, speed: 82,
    move: ['Dual Wingbeat', 'Payback'],
    moveTMs: []
  }),
  'potw-963': ensurePkmnBuilder({
    species: 'Finizen', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 60.2,
    eggBase: 'potw-963', eggGroup: ['Field', 'Water 2'], eggCycles: 20,
    evolveTo: ['potw-964'],
    pokedex: `It likes playing with others of its kind using the water ring on its tail. It uses ultrasonic waves to sense the emotions of other living creatures.`,
    hp: 70, attack: 45, defense: 40, spAttack: 45, spDefense: 40, speed: 75,
    move: ['Aqua Tail'],
    moveTMs: []
  }),
  'potw-964': ensurePkmnBuilder({
    species: 'Palafin', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 97.4, syncableForms: ['zero', 'hero'], needForm: 'zero',
    eggBase: 'potw-963', eggGroup: ['Field', 'Water 2'], eggCycles: 20,
    pokedex: `This Pokémon changes its appearance if it hears its allies calling for help. Palafin will never show anybody its moment of transformation.`,
    hp: 100, attack: 70, defense: 72, spAttack: 53, spDefense: 62, speed: 100,
    move: ['Flip Turn'],
    moveTMs: []
  }),
  'potw-964-hero': ensurePkmnBuilder({
    species: 'Palafin', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 97.4, syncableForms: ['zero', 'hero'], needForm: 'zero',
    eggBase: 'potw-963', eggGroup: ['Field', 'Water 2'], eggCycles: 20,
    pokedex: `This Pokémon’s ancient genes have awakened. It is now so extraordinarily strong that it can easily lift a cruise ship with one fin.`,
    hp: 100, attack: 160, defense: 97, spAttack: 106, spDefense: 87, speed: 100,
    move: ['Jet Punch'],
    moveTMs: []
  }),
  'potw-965': ensurePkmnBuilder({
    species: 'Varoom', type1: 'Steel', type2: 'Poison', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 35,
    eggBase: 'potw-965', eggGroup: ['Mineral'], eggCycles: 10,
    levelAt: 40, levelTo: 'potw-966',
    pokedex: `It is said that this Pokémon was born when an unknown poison Pokémon entered and inspirited an engine left at a scrap-processing factory.`,
    hp: 45, attack: 70, defense: 63, spAttack: 30, spDefense: 45, speed: 47,
    move: ['Smog', 'Gyro Ball'],
    moveTMs: []
  }),
  'potw-966': ensurePkmnBuilder({
    species: 'Revavroom', type1: 'Steel', type2: 'Poison', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 120,
    eggBase: 'potw-965', eggGroup: ['Mineral'], eggCycles: 10,
    pokedex: `It creates a gas out of poison and minerals from rocks. It then detonates the gas in its cylinders&#8212; now numbering eight&#8212;to generate energy.`,
    hp: 80, attack: 119, defense: 90, spAttack: 54, spDefense: 67, speed: 90,
    move: ['Spin Out', 'Poison Jab'],
    moveTMs: [],
    novelMoves: [[],
      ['Uproar', 'Shift Gear'],
    ],
  }),
  'potw-967': ensurePkmnBuilder({
    species: 'Cyclizar', type1: 'Dragon', type2: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 63,
    eggBase: 'potw-967', eggGroup: ['Field'], eggCycles: 15,
    pokedex: `Apparently Cyclizar has been allowing people to ride on its back since ancient times. Depictions of this have been found in 10,000-year-old murals.`,
    hp: 70, attack: 95, defense: 65, spAttack: 85, spDefense: 65, speed: 121,
    move: ['Dragon Rush', 'Double-Edge'],
    moveTMs: [],
    novelMoves: [[],
      // ['Shed Tail'],
    ],
  }),
  'potw-968': ensurePkmnBuilder({
    species: 'Orthworm', type1: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 310,
    eggBase: 'potw-968', eggGroup: ['Field'], eggCycles: 35,
    pokedex: `When attacked, this Pokémon will wield the tendrils on its body like fists and pelt the opponent with a storm of punches.`,
    hp: 70, attack: 85, defense: 145, spAttack: 60, spDefense: 55, speed: 65,
    move: ['Iron Tail'],
    moveTMs: [],
    novelMoves: [[],
      // ['Dig', 'Shed Tail']  
    ],
  }),
  'potw-969': ensurePkmnBuilder({
    species: 'Glimmet', type1: 'Rock', type2: 'Poison', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 8,
    eggBase: 'potw-969', eggGroup: ['Mineral'], eggCycles: 15,
    levelAt: 35, levelTo: 'potw-970',
    pokedex: `It absorbs nutrients from cave walls. The petals it wears are made of crystallized poison.`,
    hp: 48, attack: 35, defense: 42, spAttack: 105, spDefense: 60, speed: 60,
    move: ['Ancient Power', 'Acid Spray'],
    moveTMs: []
  }),
  'potw-970': ensurePkmnBuilder({
    species: 'Glimmora', type1: 'Rock', type2: 'Poison', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 45,
    eggBase: 'potw-969', eggGroup: ['Mineral'], eggCycles: 15,
    pokedex: `When this Pokémon detects danger, it will open up its crystalline petals and fire beams from its conical body.`,
    hp: 83, attack: 55, defense: 90, spAttack: 130, spDefense: 81, speed: 86,
    move: ['Power Gem', 'Mortal Spin'],
    moveTMs: []
  }),
  'potw-971': ensurePkmnBuilder({
    species: 'Greavard', type1: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 35,
    eggBase: 'potw-971', eggGroup: ['Field'], eggCycles: 10,
    levelAt: 30, levelTo: 'potw-972', // TODO: Only at night
    pokedex: `It is said that a dog Pokémon that died in the wild without ever interacting with a human was reborn as this Pokémon.`,
    hp: 50, attack: 61, defense: 60, spAttack: 30, spDefense: 55, speed: 34,
    move: ['Lick'],
    moveTMs: []
  }),
  'potw-972': ensurePkmnBuilder({
    species: 'Houndstone', type1: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 15,
    eggBase: 'potw-971', eggGroup: ['Field'], eggCycles: 10,
    pokedex: `Houndstone spends most of its time sleeping in graveyards. Among all the dog Pokémon, this one is most loyal to its master.`,
    hp: 72, attack: 101, defense: 100, spAttack: 50, spDefense: 97, speed: 68,
    move: ['Last Respects'],
    moveTMs: []
  }),
  'potw-973': ensurePkmnBuilder({
    species: 'Flamigo', type1: 'Flying', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 37,
    eggBase: 'potw-973', eggGroup: ['Flying'], eggCycles: 10,
    pokedex: `This Pokémon apparently ties the base of its neck into a knot so that energy stored in its belly does not escape from its beak.`,
    hp: 82, attack: 115, defense: 74, spAttack: 75, spDefense: 64, speed: 90,
    move: ['Brave Bird', 'Low Kick'],
    moveTMs: []
  }),
  'potw-974': ensurePkmnBuilder({
    species: 'Cetoddle', type1: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 45,
    eggBase: 'potw-974', eggGroup: ['Field'], eggCycles: 25, evolveTo: ['potw-975'],
    pokedex: `This species left the ocean and began living on land a very long time ago. It seems to be closely related to Wailmer.`,
    hp: 108, attack: 68, defense: 45, spAttack: 30, spDefense: 40, speed: 43,
    move: ['Ice Shard'],
    moveTMs: []
  }),
  'potw-975': ensurePkmnBuilder({
    species: 'Cetitan', type1: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 700,
    eggBase: 'potw-974', eggGroup: ['Field'], eggCycles: 25,
    pokedex: `This Pokémon wanders around snowy, icy areas. It protects its body with powerful muscles and a thick layer of fat under its skin.`,
    hp: 170, attack: 113, defense: 65, spAttack: 45, spDefense: 55, speed: 73,
    move: ['Ice Spinner'],
    moveTMs: []
  }),
  'potw-976': ensurePkmnBuilder({
    species: 'Veluza', type1: 'Water', type2: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 90,
    eggBase: 'potw-976', eggGroup: ['Water 2'], eggCycles: 10,
    pokedex: `When Veluza discards unnecessary flesh, its mind becomes honed and its psychic power increases. The spare flesh has a mild but delicious flavor.`,
    hp: 90, attack: 102, defense: 73, spAttack: 78, spDefense: 65, speed: 70,
    move: ['Liquidation', 'Psycho Cut'],
    moveTMs: [],
    novelMoves: [[],
      ['Crunch', 'Fillet Away']
    ],
  }),
  'potw-977': ensurePkmnBuilder({
    species: 'Dondozo', type1: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 220,
    eggBase: 'potw-977', eggGroup: ['Water 2'], eggCycles: 20,
    pokedex: `This Pokémon is a glutton, but it's bad at getting food. It teams up with a Tatsugiri to catch prey.`,
    hp: 150, attack: 100, defense: 115, spAttack: 65, spDefense: 65, speed: 35,
    move: ['Wave Crash'],
    moveTMs: []
  }),
  'potw-978': ensurePkmnBuilder({
    species: 'Tatsugiri', type1: 'Dragon', type2: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 8, syncableForms: ['droopy', 'curly', 'stretchy'], needForm: true,
    eggBase: 'potw-978', eggGroup: ['Water 2'], eggCycles: 35,
    pokedex: `This is a small dragon Pokémon. It lives inside the mouth of Dondozo to protect itself from enemies on the outside.`,
    hp: 68, attack: 50, defense: 60, spAttack: 120, spDefense: 95, speed: 82,
    move: ['Dragon Pulse', 'Muddy Water'],
    moveTMs: []
  }),
  'potw-979': ensurePkmnBuilder({
    species: 'Annihilape', type1: 'Fighting', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 56,
    eggBase: 'potw-056', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `When its anger rose beyond a critical point, this Pokémon gained power that is unfettered by the limits of its physical body.`,
    hp: 110, attack: 115, defense: 80, spAttack: 50, spDefense: 90, speed: 90,
    move: ['Cross Chop', 'Shadow Punch'],
    moveTMs: []
  }),
  'potw-980': ensurePkmnBuilder({
    species: 'Clodsire', type1: 'Poison', type2: 'Ground', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 223,
    eggBase: 'potw-194-paldean', eggGroup: ['Water 1', 'Field'], eggCycles: 20,
    pokedex: `When attacked, this Pokémon will retaliate by sticking thick spines out from its body. It's a risky move that puts everything on the line.`,
    hp: 130, attack: 75, defense: 60, spAttack: 45, spDefense: 100, speed: 20,
    move: ['Poison Jab', 'Stomping Tantrum'],
    moveTMs: [],
    novelMoves: [[],
      ['Megahorn', 'Amnesia']
    ],
  }),
  'potw-981': ensurePkmnBuilder({
    species: 'Farigiraf', type1: 'Normal', type2: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 160,
    eggBase: 'potw-203', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `Now that the brain waves from the head and tail are synced up, the psychic power of this Pokémon is 10 times stronger than Girafarig's.`,
    hp: 120, attack: 90, defense: 70, spAttack: 110, spDefense: 70, speed: 60,
    move: ['Stomp', 'Twin Beam'],
    moveTMs: []
  }),
  'potw-982': ensurePkmnBuilder({
    species: 'Dudunsparce', type1: 'Normal', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    syncableForms: [...Array(99).fill('two_segment'), 'three_segment'], needForm: true,
    weight: 47.4,
    eggBase: 'potw-206', eggGroup: ['Field'], eggCycles: 20,
    pokedex: `This Pokémon uses its hard tail to make its nest by boring holes into bedrock deep underground. The nest can reach lengths of over six miles.`,
    hp: 125, attack: 100, defense: 80, spAttack: 85, spDefense: 75, speed: 55,
    move: ['Hyper Drill'],
    moveTMs: []
  }),
  'potw-983': ensurePkmnBuilder({
    species: 'Kingambit', type1: 'Dark', type2: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 120,
    eggBase: 'potw-624', eggGroup: ['Human-Like'], eggCycles: 10,
    pokedex: `Only a Bisharp that stands above all others in its vast army can evolve into Kingambit.`,
    hp: 100, attack: 135, defense: 120, spAttack: 60, spDefense: 85, speed: 50,
    move: ['Kowtow Cleave', 'Iron Head'],
    moveTMs: []
  }),
  'potw-984': ensurePkmnBuilder({
    species: 'Great Tusk', type1: 'Ground', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 320,
    eggGroup: [], eggCycles: 25,
    pokedex: `Sightings of this Pokémon have occurred in recent years. The name Great Tusk was taken from a creature listed in a certain book.`,
    hp: 115, attack: 131, defense: 131, spAttack: 53, spDefense: 53, speed: 87,
    move: ['Headlong Rush', 'Close Combat'],
    moveTMs: []
  }),
  'potw-985': ensurePkmnBuilder({
    species: 'Scream Tail', type1: 'Fairy', type2: 'Psychic', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 8,
    eggGroup: [], eggCycles: 25,
    pokedex: `There has been only one reported sighting of this Pokémon. It resembles a mysterious creature depicted in an old expedition journal.`,
    hp: 115, attack: 65, defense: 99, spAttack: 65, spDefense: 115, speed: 111,
    move: ['Play Rough', 'Psychic Fangs'],
    moveTMs: []
  }),
  'potw-986': ensurePkmnBuilder({
    species: 'Brute Bonnet', type1: 'Grass', type2: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 21,
    eggGroup: [], eggCycles: 25,
    pokedex: `It is possible that the creature listed as Brute Bonnet in a certain book could actually be this Pokémon.`,
    hp: 111, attack: 127, defense: 99, spAttack: 79, spDefense: 99, speed: 55,
    move: ['Giga Drain', 'Sucker Punch'],
    moveTMs: []
  }),
  'potw-987': ensurePkmnBuilder({
    species: 'Flutter Mane', type1: 'Ghost', type2: 'Fairy', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 4,
    eggGroup: [], eggCycles: 25,
    pokedex: `This Pokémon has characteristics similar to those of Flutter Mane, a creature mentioned in a certain book.`,
    hp: 55, attack: 55, defense: 55, spAttack: 135, spDefense: 135, speed: 135,
    move: ['Phantom Force', 'Moonblast'],
    moveTMs: []
  }),
  'potw-988': ensurePkmnBuilder({
    species: 'Slither Wing', type1: 'Bug', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 92,
    eggGroup: [], eggCycles: 25,
    pokedex: `This mysterious Pokémon has some similarities to a creature that an old book introduced as Slither Wing.`,
    hp: 85, attack: 135, defense: 79, spAttack: 85, spDefense: 105, speed: 81,
    move: ['Leech Life', 'Low Sweep'],
    moveTMs: []
  }),
  'potw-989': ensurePkmnBuilder({
    species: 'Sandy Shocks', type1: 'Electric', type2: 'Ground', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 60,
    eggGroup: [], eggCycles: 25,
    pokedex: `No records exist of this Pokémon being caught. Data is lacking, but the Pokémon's traits match up with a creature shown in an expedition journal.`,
    hp: 85, attack: 81, defense: 97, spAttack: 121, spDefense: 85, speed: 101,
    move: ['Zap Cannon', 'Stomping Tantrum'],
    moveTMs: []
  }),
  'potw-990': ensurePkmnBuilder({
    species: 'Iron Treads', type1: 'Ground', type2: 'Steel', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 240,
    eggGroup: [], eggCycles: 25,
    pokedex: `This Pokémon closely resembles a scientific weapon that a paranormal magazine claimed was sent to this planet by aliens.`,
    hp: 90, attack: 112, defense: 120, spAttack: 72, spDefense: 70, speed: 106,
    move: ['Stomping Tantrum', 'Steel Roller'],
    moveTMs: []
  }),
  'potw-991': ensurePkmnBuilder({
    species: 'Iron Bundle', type1: 'Ice', type2: 'Water', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 11,
    eggGroup: [], eggCycles: 25,
    pokedex: `Its shape is similar to a robot featured in a paranormal magazine article. The robot was said to have been created by an ancient civilization.`,
    hp: 56, attack: 80, defense: 114, spAttack: 124, spDefense: 60, speed: 136,
    move: ['Blizzard', 'Hydro Pump'],
    moveTMs: [],
  }),
  'potw-992': ensurePkmnBuilder({
    species: 'Iron Hands', type1: 'Fighting', type2: 'Electric', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 380.7,
    eggGroup: [], eggCycles: 25,
    pokedex: `It is very similar to a cyborg covered exclusively by a paranormal magazine. The cyborg was said to be the modified form of a certain athlete.`,
    hp: 154, attack: 140, defense: 108, spAttack: 50, spDefense: 68, speed: 50,
    move: ['Force Palm', 'Wild Charge'],
    moveTMs: [],
    novelMoves: [[],
      ['Heavy Slam', 'Belly Drum'],
    ],
  }),
  'potw-993': ensurePkmnBuilder({
    species: 'Iron Jugulis', type1: 'Dark', type2: 'Flying', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 111,
    eggGroup: [], eggCycles: 25,
    pokedex: `It resembles a certain Pokémon introduced in a paranormal magazine, described as the offspring of a Hydreigon that fell in love with a robot.`,
    hp: 94, attack: 80, defense: 86, spAttack: 122, spDefense: 80, speed: 108,
    move: ['Dark Pulse', 'Air Slash'],
    moveTMs: []
  }),
  'potw-994': ensurePkmnBuilder({
    species: 'Iron Moth', type1: 'Fire', type2: 'Poison', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 36,
    eggGroup: [], eggCycles: 25,
    pokedex: `This Pokémon resembles an unknown object described in a paranormal magazine as a UFO sent to observe humanity.`,
    hp: 80, attack: 70, defense: 60, spAttack: 140, spDefense: 110, speed: 110,
    move: ['Fiery Dance', 'Sludge Wave'],
    moveTMs: []
  }),
  'potw-995': ensurePkmnBuilder({
    species: 'Iron Thorns', type1: 'Rock', type2: 'Electric', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 303,
    eggGroup: [], eggCycles: 25,
    pokedex: `It has some similarities to a Pokémon introduced in a dubious magazine as a Tyranitar from one billion years into the future.`,
    hp: 100, attack: 134, defense: 110, spAttack: 70, spDefense: 84, speed: 72,
    move: ['Stone Edge', 'Wild Charge'],
    moveTMs: []
  }),
  'potw-996': ensurePkmnBuilder({
    species: 'Frigibax', type1: 'Dragon', type2: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 17,
    eggBase: 'potw-996', eggGroup: ['Dragon'], eggCycles: 20,
    levelAt: 35, levelTo: 'potw-997',
    pokedex: `Frigibax absorbs heat through its dorsal fin and converts the heat into ice energy. The higher the temperature, the more energy Frigibax stores.`,
    hp: 65, attack: 75, defense: 45, spAttack: 35, spDefense: 45, speed: 55,
    move: ['Dragon Tail', 'Icy Wind'],
    moveTMs: []
  }),
  'potw-997': ensurePkmnBuilder({
    species: 'Arctibax', type1: 'Dragon', type2: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 30,
    eggBase: 'potw-996', eggGroup: ['Dragon'], eggCycles: 20,
    levelAt: 54, levelTo: 'potw-998',
    pokedex: `Arctibax freezes the air around it, protecting its face with an ice mask and turning its dorsal fin into a blade of ice.`,
    hp: 90, attack: 95, defense: 66, spAttack: 45, spDefense: 65, speed: 62,
    move: ['Dragon Tail', 'Ice Fang'],
    moveTMs: []
  }),
  'potw-998': ensurePkmnBuilder({
    species: 'Baxcalibur', type1: 'Dragon', type2: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 210,
    eggBase: 'potw-996', eggGroup: ['Dragon'], eggCycles: 20,
    pokedex: `This Pokémon blasts cryogenic air out from its mouth. This air can instantly freeze even liquid-hot lava.`,
    hp: 115, attack: 145, defense: 92, spAttack: 75, spDefense: 86, speed: 87,
    move: ['Glaive Rush', 'Icicle Crash'],
    moveTMs: []
  }),
  'potw-999': ensurePkmnBuilder({
    species: 'Gimmighoul', type1: 'Ghost',
    shiny: 'FALSE', weight: 3.8, syncableForms: ['chest', 'roaming'], needForm: 'chest',
    tiers: [/* 'SV Cup', 'SV DLC Cup' */],
    evolveTo: ['potw-1000'], eggCycles: -1,
    pokedex: `This Pokémon was born inside a treasure chest about 1,500 years ago. It sucks the life-force out of scoundrels who try to steal the treasure.`,
    hp: 45, attack: 30, defense: 70, spAttack: 75, spDefense: 70, speed: 10,
    move: ['Astonish'],
    moveTMs: [],
  }),
  'potw-999-chest': ensurePkmnBuilder({
    species: 'Gimmighoul', type1: 'Ghost',
    shiny: 'FALSE', weight: 3.8,
    tiers: [/* 'SV Cup', 'SV DLC Cup' */],
    evolveTo: ['potw-1000'], eggCycles: -1,
    pokedex: `This Pokémon was born inside a treasure chest about 1,500 years ago. It sucks the life-force out of scoundrels who try to steal the treasure.`,
    hp: 45, attack: 30, defense: 70, spAttack: 75, spDefense: 70, speed: 10,
    move: ['Astonish'],
    moveTMs: [],
  }),
  'potw-999-roaming': ensurePkmnBuilder({
    species: 'Gimmighoul', type1: 'Ghost',
    shiny: 'FALSE', weight: 3.8,
    tiers: [/* 'SV Cup', 'SV DLC Cup' */],
    evolveTo: ['potw-1000'], eggCycles: -1,
    pokedex: `This Pokémon was born from passion that seeped into a coin. It wanders, apparently seeking to return to the treasure chest it once inhabited.`,
    hp: 45, attack: 30, defense: 25, spAttack: 75, spDefense: 45, speed: 80,
    move: ['Astonish'],
    moveTMs: [],
  }),
  'potw-1000': ensurePkmnBuilder({
    species: 'Gholdengo', type1: 'Steel', type2: 'Ghost', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 30, eggCycles: -1,
    pokedex: `Its body seems to be made up of 1,000 coins. This Pokémon gets along well with others and is quick to make friends with anybody.`,
    hp: 87, attack: 60, defense: 95, spAttack: 133, spDefense: 91, speed: 84,
    move: ['Make It Rain', 'Shadow Ball'],
    moveTMs: []
  }),
  'potw-1001': ensurePkmnBuilder({
    species: 'Wo-Chien', type1: 'Dark', type2: 'Grass', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 74.2,
    eggGroup: [], eggCycles: 25,
    pokedex: `The grudge of a person punished for writing the king's evil deeds upon wooden tablets has clad itself in dead leaves to become a Pokémon.`,
    hp: 85, attack: 85, defense: 100, spAttack: 95, spDefense: 135, speed: 70,
    move: ['Power Whip', 'Ruination'],
    moveTMs: []
  }),
  'potw-1002': ensurePkmnBuilder({
    species: 'Chien-Pao', type1: 'Dark', type2: 'Ice', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 152.2,
    eggGroup: [], eggCycles: 25,
    pokedex: `This Pokémon can control 100 tons of fallen snow. It plays around innocently by leaping in and out of avalanches it has caused.`,
    hp: 80, attack: 120, defense: 80, spAttack: 90, spDefense: 65, speed: 135,
    move: ['Sheer Cold', 'Ruination'],
    moveTMs: []
  }),
  'potw-1003': ensurePkmnBuilder({
    species: 'Ting-Lu', type1: 'Dark', type2: 'Ground', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 699.7,
    eggGroup: [], eggCycles: 25,
    pokedex: `The fear poured into an ancient ritual vessel has clad itself in rocks and dirt to become a Pokémon.`,
    hp: 155, attack: 110, defense: 125, spAttack: 55, spDefense: 80, speed: 45,
    move: ['Fissure', 'Ruination'],
    moveTMs: []
  }),
  'potw-1004': ensurePkmnBuilder({
    species: 'Chi-Yu', type1: 'Dark', type2: 'Fire', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 4.9,
    eggGroup: [], eggCycles: 25,
    pokedex: `It controls flames burning at over 5,400 degrees Fahrenheit. It casually swims through the sea of lava it creates by melting rock and sand.`,
    hp: 55, attack: 80, defense: 80, spAttack: 135, spDefense: 120, speed: 100,
    move: ['Lava Plume', 'Ruination'],
    moveTMs: []
  }),
  'potw-1005': ensurePkmnBuilder({
    species: 'Roaring Moon', type1: 'Dragon', type2: 'Dark', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 380,
    eggGroup: [], eggCycles: 25,
    pokedex: `It is possible that this is the creature listed as Roaring Moon in an expedition journal that still holds many mysteries.`,
    hp: 105, attack: 139, defense: 71, spAttack: 55, spDefense: 101, speed: 119,
    move: ['Dragon Rush', 'Night Slash'],
    moveTMs: []
  }),
  'potw-1006': ensurePkmnBuilder({
    species: 'Iron Valiant', type1: 'Fairy', type2: 'Fighting', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 35,
    eggGroup: [], eggCycles: 25,
    pokedex: `It has some similarities to a mad scientist's invention covered in a paranormal magazine.`,
    hp: 74, attack: 130, defense: 90, spAttack: 120, spDefense: 60, speed: 116,
    move: ['Spirit Break', 'Close Combat'],
    moveTMs: []
  }),
  'potw-1007': ensurePkmnBuilder({
    species: 'Koraidon', type1: 'Fighting', type2: 'Dragon', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 303,
    eggGroup: [], eggCycles: 25,
    pokedex: `This seems to be the Winged King mentioned in an old expedition journal. It was said to have split the land with its bare fists.`,
    hp: 100, attack: 135, defense: 115, spAttack: 85, spDefense: 100, speed: 135,
    move: ['Collision Course', 'Outrage'],
    moveTMs: []
  }),
  'potw-1008': ensurePkmnBuilder({
    species: 'Miraidon', type1: 'Electric', type2: 'Dragon', 
    tiers: [/* 'SV Cup', 'SV DLC Cup' */], shiny: 'FALSE',
    weight: 240,
    eggGroup: [], eggCycles: 25,
    pokedex: `Much remains unknown about this creature. It resembles Cyclizar, but it is far more ruthless and powerful.`,
    hp: 100, attack: 85, defense: 100, spAttack: 135, spDefense: 115, speed: 135,
    move: ['Electro Drift', 'Dragon Pulse'],
    moveTMs: []
  }),
  'potw-1009': ensurePkmnBuilder({
    species: 'Walking Wake', type1: 'Water', type2: 'Dragon',
    shiny: 'SYNCABLE', weight: 280, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `An unusual Pokémon of unknown origins.`,
    hp: 99, attack: 83, defense: 91, spAttack: 125, spDefense: 83, speed: 109,
    move: ['Hydro Steam', 'Dragon Pulse'],
    moveTMs: [],
  }),
  'potw-1010': ensurePkmnBuilder({
    species: 'Iron Leaves', type1: 'Grass', type2: 'Psychic',
    shiny: 'SYNCABLE', weight: 125, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `An unusual Pokémon of unknown origins.`,
    hp: 90, attack: 130, defense: 88, spAttack: 70, spDefense: 108, speed: 104,
    move: ['Solar Blade', 'Psyblade'],
    moveTMs: [],
  }),
  'potw-1011': ensurePkmnBuilder({
    species: 'Dipplin', type1: 'Grass', type2: 'Dragon',
    shiny: 'SYNCABLE', weight: 4.4, eggCycles: 20, eggBase: 'potw-840', eggGroup: ['Grass', 'Dragon'],
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `Dipplin is two creatures in one Pokémon. Its evolution was triggered by a special apple grown only in one place.`,
    hp: 80, attack: 80, defense: 110, spAttack: 95, spDefense: 80, speed: 40,
    move: ['Syrup Bomb', 'Dragon Pulse'],
    moveTMs: [],
  }),
  'potw-1012': ensurePkmnBuilder({
    species: 'Poltchageist', type1: 'Grass', type2: 'Ghost',
    shiny: 'FALSE', weight: 1.1, eggCycles: 20, eggBase: 'potw-1012', eggGroup: ['Mineral', 'Amorphous'],
    tiers: [/* 'SV DLC Cup' */],
    syncableForms: [...Array(30).fill('counterfeit'), 'artisan'], needForm: true, evolveTo: ['potw-1013'],
    pokedex: `Supposedly, the regrets of a tea ceremony master who died before perfecting his craft lingered in some matcha and became a Pokémon.`,
    hp: 40, attack: 45, defense: 45, spAttack: 74, spDefense: 54, speed: 50,
    move: ['Mega Drain', 'Hex'],
    moveTMs: [],
  }),
  'potw-1013': ensurePkmnBuilder({
    species: 'Sinistcha', type1: 'Grass', type2: 'Ghost',
    shiny: 'FALSE', weight: 2.2, eggCycles: 20, eggBase: 'potw-1012', eggGroup: ['Mineral', 'Amorphous'],
    tiers: [/* 'SV DLC Cup' */],
    syncableForms: [...Array(30).fill('unremarkable'), 'masterpiece'], needForm: true, evolveTo: ['potw-1013'],
    pokedex: `It pretends to be tea, trying to fool people into drinking it so it can drain their life-force. Its ruse is generally unsuccessful.`,
    hp: 71, attack: 60, defense: 106, spAttack: 121, spDefense: 80, speed: 70,
    move: ['Matcha Gotcha', 'Shadow Ball'],
    moveTMs: [],
  }),
  'potw-1014': ensurePkmnBuilder({
    species: 'Okidogi', type1: 'Poison', type2: 'Fighting',
    shiny: 'FALSE', weight: 92, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `After all its muscles were stimulated by the toxic chain around its neck, Okidogi transformed and gained a powerful physique.`,
    hp: 88, attack: 128, defense: 115, spAttack: 58, spDefense: 86, speed: 80,
    move: ['Poison Jab', 'Force Palm'],
    moveTMs: [],
  }),
  'potw-1015': ensurePkmnBuilder({
    species: 'Munkidori', type1: 'Poison', type2: 'Psychic',
    shiny: 'FALSE', weight: 12.2, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `The chain is made from toxins that enhance capabilities. It stimulated Munkidori's brain and caused the Pokémon's psychic powers to bloom.`,
    hp: 88, attack: 75, defense: 66, spAttack: 130, spDefense: 90, speed: 106,
    move: ['Sludge Wave', 'Future Sight'],
    moveTMs: [],
  }),
  'potw-1016': ensurePkmnBuilder({
    species: 'Fezandipiti', type1: 'Poison', type2: 'Fairy',
    shiny: 'FALSE', weight: 30.1, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `Fezandipiti owes its beautiful looks and lovely voice to the toxic stimulants emanating from the chain wrapped around its body.`,
    hp: 88, attack: 91, defense: 82, spAttack: 70, spDefense: 125, speed: 99,
    move: ['Cross Poison', 'Moonblast'],
    moveTMs: [],
  }),
  'potw-1017': ensurePkmnBuilder({
    species: 'Ogerpon', type1: 'Grass',
    shiny: 'FALSE', weight: 39.8, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `This Pokémon's type changes based on which mask it's wearing. It confounds its enemies with nimble movements and kicks.`,
    hp: 80, attack: 120, defense: 84, spAttack: 60, spDefense: 96, speed: 110,
    move: ['Ivy Cudgel'],
    moveTMs: [],
  }),
  'potw-1096': ensurePkmnBuilder({
    species: 'Raging Bolt', type1: 'Electric', type2: 'Dragon',
    shiny: 'FALSE', weight: 39.8, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `This Pokémon's type changes based on which mask it's wearing. It confounds its enemies with nimble movements and kicks.`,
    hp: 80, attack: 120, defense: 84, spAttack: 60, spDefense: 96, speed: 110,
    move: ['Vine Whip'],
    moveTMs: [],
  }),
  'potw-1097': ensurePkmnBuilder({
    species: 'Iron Crown', type1: 'Psychic', type2: 'Steel',
    shiny: 'FALSE', weight: 39.8, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `This Pokémon's type changes based on which mask it's wearing. It confounds its enemies with nimble movements and kicks.`,
    hp: 80, attack: 120, defense: 84, spAttack: 60, spDefense: 96, speed: 110,
    // move: ['Ivy Cudgel'],
    move: ['Vine Whip'],
    moveTMs: [],
  }),
  'potw-1098': ensurePkmnBuilder({
    species: 'Archaludon', type1: 'Steel', type2: 'Dragon',
    shiny: 'FALSE', weight: 39.8, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `This Pokémon's type changes based on which mask it's wearing. It confounds its enemies with nimble movements and kicks.`,
    hp: 80, attack: 120, defense: 84, spAttack: 60, spDefense: 96, speed: 110,
    // move: ['Ivy Cudgel'],
    move: ['Vine Whip'],
    moveTMs: [],
  }),
  'potw-1099': ensurePkmnBuilder({
    species: 'Terapagos', type1: 'Grass',
    shiny: 'FALSE', weight: 39.8, eggCycles: 40,
    tiers: [/* 'SV DLC Cup' */],
    pokedex: `This Pokémon's type changes based on which mask it's wearing. It confounds its enemies with nimble movements and kicks.`,
    hp: 80, attack: 120, defense: 84, spAttack: 60, spDefense: 96, speed: 110,
    // move: ['Ivy Cudgel'],
    move: ['Vine Whip'],
    moveTMs: [],
  }),
}

// Alternate forms are mostly clones of the original
paldeaBuilder['potw-925-family_of_three'] = {...paldeaBuilder['potw-925']}
paldeaBuilder['potw-925-family_of_three'].pokedex = `They build huge nests with many rooms that are used for different purposes, such as eating and sleeping.`

paldeaBuilder['potw-982-three_segment'] = {...paldeaBuilder['potw-982']}
paldeaBuilder['potw-982-three_segment'].pokedex = `The gentle Dudunsparce will put Pokémon that wander into its nest onto its back and carry them to the entrance.`

paldeaBuilder['potw-1012-artisan'] = {...paldeaBuilder['potw-1012']}
paldeaBuilder['potw-1012-artisan'].pokedex = `It sprinkles some of its powdery body onto food and drains the life-force from those who so much as lick it.`

paldeaBuilder['potw-1013-masterpiece'] = {...paldeaBuilder['potw-1013']}
paldeaBuilder['potw-1013-masterpiece'].pokedex = `It lives inside a superb teacup that was crafted by a potter of great renown. Collectors positively adore this Pokémon.`

